## Import library

In [1]:
import pandas as pd

## Load datasets

In [2]:
transactions_df = pd.read_csv("../datasets/transactions_master.csv")
risk_df = pd.read_csv("../datasets/fraud_risk_scores.csv")

## Check shapes

In [3]:
print(transactions_df.shape)
print(risk_df.shape)

(1852394, 24)
(370479, 4)

## Inspect columns

In [4]:
transactions_df.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud', 'dataset_type'],
      dtype='object')

In [5]:
risk_df.columns

Index(['actual_fraud', 'risk_score', 'risk_category', 'alert'], dtype='object')

## Preview datasets

In [6]:
transactions_df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,dataset_type
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,train
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,train
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,train
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,train
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,train

In [7]:
risk_df.head()

   actual_fraud  risk_score risk_category     alert
0             0         0.0           Low  LOW RISK
1             0         0.0           Low  LOW RISK
2             0         0.0           Low  LOW RISK
3             0         1.0           Low  LOW RISK
4             0         0.0           Low  LOW RISK

## Check MySQL connection libraries

In [8]:
#import sqlalchemy
#print(sqlalchemy.__version__)

In [9]:
#%pip install sqlalchemy pymysql

In [10]:
import sqlalchemy
print(sqlalchemy.__version__)

2.0.51

In [11]:
import pymysql
print("PyMySQL Installed Successfully")

PyMySQL Installed Successfully

## Create Proper MySQL Connection

In [20]:
from urllib.parse import quote_plus
from sqlalchemy import create_engine

In [21]:
password = quote_plus("Swatika@2001")

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost:3306/fraud_analytics_db"
)

In [22]:
with engine.connect() as conn:
    print("Database Connection Successful")

Database Connection Successful

## Load datasets into MySQL

In [23]:
transactions_df.shape

(1852394, 24)

In [24]:
risk_df.shape

(370479, 4)

In [25]:
transactions_df.memory_usage(deep=True).sum() / 1024**2

np.float64(1757.1567859649658)

In [26]:
risk_df.memory_usage(deep=True).sum() / 1024**2

np.float64(49.91984939575195)

 ## Create tables using sample data

## Load only 1000 rows first of transactions_master

In [27]:
sample_transactions = transactions_df.head(1000)

In [28]:
sample_transactions.to_sql(
    "transactions_master",
    con=engine,
    if_exists="replace",
    index=False
)

print("Table Created Successfully")

Table Created Successfully

## Load data of fraud_risk_scores

In [29]:
risk_df.to_sql(
    "fraud_risk_scores",
    con=engine,
    if_exists="replace",
    index=False
)

print("Risk Table Created Successfully")

Risk Table Created Successfully

In [30]:
chunk_size = 50000

for i, chunk_start in enumerate(
    range(0, len(transactions_df), chunk_size)
):
    
    chunk = transactions_df.iloc[
        chunk_start : chunk_start + chunk_size
    ]
    
    if i == 0:
        
        chunk.to_sql(
            "transactions_master",
            con=engine,
            if_exists="replace",
            index=False
        )
        
    else:
        
        chunk.to_sql(
            "transactions_master",
            con=engine,
            if_exists="append",
            index=False
        )
    
    print(
        f"Loaded rows: {chunk_start + len(chunk):,}"
    )

print("Full Dataset Loaded Successfully")

Loaded rows: 50,000
Loaded rows: 100,000
Loaded rows: 150,000
Loaded rows: 200,000
Loaded rows: 250,000
Loaded rows: 300,000
Loaded rows: 350,000
Loaded rows: 400,000
Loaded rows: 450,000
Loaded rows: 500,000
Loaded rows: 550,000
Loaded rows: 600,000
Loaded rows: 650,000
Loaded rows: 700,000
Loaded rows: 750,000
Loaded rows: 800,000
Loaded rows: 850,000
Loaded rows: 900,000
Loaded rows: 950,000
Loaded rows: 1,000,000
Loaded rows: 1,050,000
Loaded rows: 1,100,000
Loaded rows: 1,150,000
Loaded rows: 1,200,000
Loaded rows: 1,250,000
Loaded rows: 1,300,000
Loaded rows: 1,350,000
Loaded rows: 1,400,000
Loaded rows: 1,450,000
Loaded rows: 1,500,000
Loaded rows: 1,550,000
Loaded rows: 1,600,000
Loaded rows: 1,650,000
Loaded rows: 1,700,000
Loaded rows: 1,750,000
Loaded rows: 1,800,000
Loaded rows: 1,850,000
Loaded rows: 1,852,394
Full Dataset Loaded Successfully